import type { CSSProperties } from "react";
import MARK from "@/lib/monogram-paths.json";

/**
 * The BA monogram, drawn like a pen would: thin upstrokes, heavy downstrokes. The B's lower bowl
 * sheds a hairline that becomes the A's crossbar (the knot where the letters meet), and the A's
 * right leg ends in a flourish that leaves the mark as the site's thread.
 *
 * Shapes are generated by scripts/monogram.mjs; edit the centerlines there, not the paths here.
 * `small` is the same drawing with every stroke heavier, for 16–28px.
 */
export const MONOGRAM = MARK;

/** Where the flourish leaves the mark, as fractions of the mark's box. */
export const MONOGRAM_EXIT = {
  x: MARK.exit[0] / 128,
  y: MARK.exit[1] / 96,
};

// Stroke order when it draws itself: the B, then the A's rise, the bridge, and last the fall,
// whose flourish hands off to the thread.
const DRAW_DELAY: Record<string, number> = {
  spine: 0,
  upper: 220,
  lower: 440,
  rise: 680,
  bridge: 860,
  fall: 1000,
};

type Stroke = keyof typeof MARK.shapes;

export function Monogram({
  className,
  title = "Bhakti Ahir",
  draw = false,
  small = false,
}: {
  className?: string;
  title?: string | null;
  /** Traces each stroke, then fills it (instant under reduced motion). */
  draw?: boolean;
  small?: boolean;
}) {
  const shapes = small ? MARK.small : MARK.shapes;
  const order = MARK.order as Stroke[];
  return (
    <svg
      viewBox={MARK.viewBox}
      className={className}
      role={title ? "img" : undefined}
      aria-label={title ?? undefined}
      aria-hidden={title ? undefined : true}
    >
      {draw &&
        order.map((k) => (
          <path
            key={`line-${k}`}
            d={MARK.lines[k]}
            pathLength={1}
            fill="none"
            stroke="currentColor"
            strokeWidth={1.1}
            strokeLinecap="round"
            className="mono-line"
            style={{ "--delay": `${DRAW_DELAY[k]}ms` } as CSSProperties}
          />
        ))}
      {order.map((k) => (
        <path
          key={k}
          d={shapes[k]}
          fill="currentColor"
          className={draw ? "mono-fill" : undefined}
          style={
            draw
              ? ({ "--delay": `${DRAW_DELAY[k] + 420}ms` } as CSSProperties)
              : undefined
          }
        />
      ))}
    </svg>
  );
}
